### ISSUE TITLE
Unable to load addon script from path 'res://addons/godot_wfc_mono_godot_wfc_mono.cs' 

### ISSUE THREAD

**Issue by Sunnigen** [theBGPguy/Godot_WaveFunctionCollapse#1]
**Version**: Godot_v3.5.1-stable_mono_win64

**Steps to Reproduce:**
1. Download fresh .zip from this repo
2. Load project from Godot-mono

When I load the project and go into it. I immediately am greeted with this error
![image](https://user-images.githubusercontent.com/27396065/197368658-f8afb9ab-0950-48af-b32c-bfb72b779380.png)

 When I step into `godot_wfc_mono.cs` I see this:

```
using Godot;
using System;

[Tool]
public class godot_wfc_mono : EditorPlugin
{
    // Declare member variables here. Examples:
    // private int a = 2;
    // private string b = "text";

    // Called when the node enters the scene tree for the first time.
    public override void _Ready()
    {
        GD.Print("Hello World!");
    }

//  // Called every frame. 'delta' is the elapsed time since the previous frame.
//  public override void _Process(float delta)
//  {
//      
//  }
}
```
Even went I comment out every line of code. I still get the same error.
I know this project is from quite a while ago, but I haven't been able to find a "hopeful" looking godot WFC project meant for 2D. 

Would appreciate if this was addressed!

**Comment by theBGPguy** [comment]
I have gone through the steps to reproduce, and I have indeed gotten that same error.

The error you're reporting arises because the C# files you download are not compiled yet, I believe.

Clicking the "Build" button in the top-right corner of the editor (assuming it is the Mono version) will have the editor build all the files. If that works, and it finishes successfully, go to "Project > Project Settings...",

![image](https://user-images.githubusercontent.com/33042431/197420487-1a18648e-1c01-4a83-bc02-9b00e66bd7b6.png)

then in the pop-up, click the "Plugins" tab and under the "Status" column, check the box that is labeled "Activate".

![image](https://user-images.githubusercontent.com/33042431/197420510-788df2eb-d6f3-489e-ba7d-f89083576d3b.png)

Assuming Mono built the C# files, the plugin should enable properly. Running the `main.tscn` should then show a screen with orange/brown bricks. Pressing "Space" will have the scene re-generate the image.

If you do not have the "Build" button, but know you're running the Mono version of the editor, try creating a C# script file. Godot will go through the steps it needs to and the button _should_ appear.

(You know what? I'll update the README with this information.)

**Comment by theBGPguy** [comment]
I hope this helps you.
